# 1. [20 pts] 
Define each of the following machine learning terms:
    - dataset
    - training, testing, validation dataset
    - ground truth, label
    - pre-processing, feature, numerical, nominal
    - decision surface
    - model validation, accuracy, cross-validation

Dataset: Preferably untouched raw information (images, csv, etc)

Training, Testing, Validation Dataset: The training dataset is the portion used to train a model, while the testing dataset is the non-overlapping portion used to test the trained model. A validation data set is reserved for the final tuned model, and contains data that the model has not seen before (has neither been trained or tested with).

Ground Truth, Label: This is the known correct result for the data field that the model is being trained to predict.

Pre-processing, Feature, Numerical, Nominal: Prep-processing is the set of steps needed to prune erroneous data points (duplicates, outliers, etc) and put it into a format that a ML model will accept (flattening, etc). A feature is a specific field that each data point has (Person might be the data point, and Age, Height might be the features). Numerical data consist of Integers and Floats, used in fields that are represented with numbers. Nominal data are essentially anything other than numerical; they can be True/False (boolean), or strings such as the title of a company, a street name, etc.

Decision Surface: A decision surface is the divider for a classifier, this can be a line for 2-D data, a plane for 3-D, or a hyperplane for n-D data.

Model Validation, Accuracy, Cross-validation: Model validation consists of testing a model with real world data to see if the models predictions are realistic. Model accuracy is calculated by ( TP + TN ) / ( TP + FP + TN + FN ). Cross validation consists of partitioning a set of data into multiple parts, then training on one part, and testing on another, and rotating through the partitions, averaging the validation/test results to estimate predictive performance.

# 2. [20 pts] 
Pick two of the Scikit-learn datasets which are already included in the library (i.e. the ones with datasets_load_) and find out the following:
    - the number of data points
    - the number of features and their types
    - the number and name of categories (i.e. the target field)
    - the mean (or mode if nominal) of the first two features

In [3]:
import numpy as np

In [4]:
from sklearn.datasets import load_boston
bostonDict = load_boston( )

In [11]:
bostonDict.keys( )

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])

In [41]:
print( 'In \'load_boston\' there are ', bostonDict[ 'data' ].shape[ 0 ], ' data points'  )
print( '\'load_boston\' has ', np.count_nonzero( bostonDict[ 'feature_names' ] ), ' features: ',
    bostonDict[ 'feature_names'], ' of data type ', bostonDict[ 'feature_names' ].dtype )
print( 'From the \'DESCR\' feature, the target name is \'Median Value\' and ranges from 5-50, with ',
    bostonDict[ 'target' ].shape[ 0 ], ' data points.')
print( 'The mean/mode of the first two features, ', bostonDict[ 'feature_names' ][0], ', and ',
    bostonDict[ 'feature_names' ][1], ' are: ', np.mean( bostonDict[ 'data' ][0] ), ' and ',
    np.mean( bostonDict[ 'data' ][1] ), '.' )

In 'load_boston' there are  506  data points
'load_boston' has  13  features:  ['CRIM' 'ZN' 'INDUS' 'CHAS' 'NOX' 'RM' 'AGE' 'DIS' 'RAD' 'TAX' 'PTRATIO'
 'B' 'LSTAT']  of data type  <U7
From the 'DESCR' feature, the target name is 'Median Value' and ranges from 5-50, with  506  data points.
The mean/mode of the first two features,  CRIM , and  ZN  are:  62.37687076923077  and  58.89957 .

In [5]:
from sklearn.datasets import load_diabetes
diabetesDict = load_diabetes( )

In [43]:
diabetesDict.keys( )

dict_keys(['data', 'target', 'DESCR', 'feature_names', 'data_filename', 'target_filename'])

In [59]:
print( 'In \'load_diabetes\' there are ', diabetesDict[ 'data' ].shape[ 0 ], ' data points'  )
print( '\'load_diabetes\' has ', np.count_nonzero( diabetesDict[ 'feature_names' ] ), ' features: ',
    diabetesDict[ 'feature_names'], ' of data type ', diabetesDict[ 'data' ][ 0 ].dtype )
print( 'From the \'DESCR\' feature, the target name is \'disease progression\' and ranges from 25-346, with ',
    diabetesDict[ 'target' ].shape[ 0 ], ' data points.')
print( 'The mean/mode of the first two features, ', diabetesDict[ 'feature_names' ][0], ', and ',
    diabetesDict[ 'feature_names' ][1], ' are: ', np.mean( diabetesDict[ 'data' ][0] ), ' and ',
    np.mean( diabetesDict[ 'data' ][1] ), '.' )
print( 'These look strange, but from \'DESCR\': First 10 columns are numeric predictive values')

In 'load_diabetes' there are  442  data points
'load_diabetes' has  10  features:  ['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']  of data type  float64
From the 'DESCR' feature, the target name is 'disease progression' and ranges from 25-346, with  442  data points.
The mean/mode of the first two features,  age , and  sex  are:  0.004954951349104548  and  -0.027755322489696088 .
These look strange, but from 'DESCR': First 10 columns are numeric predictive values

# 3. [40 pts] 
Implement a Pearson correlation program from scratch to look at the correlations between the features of Admission_Predict.csv dataset file (not provided, you have to download it by yourself by following the instructions in the module Jupyter notebook). Display the correlation matrix where each row and column are the features, which should be an 8 by 8 matrix (should we use 'Serial no'?). You can use pandas DataFrame.corr() to verify correctness of yours.

Observe that the diagonal of this matrix should have all 1's and explain why? Since the last column can be used as the target (dependent) variable, what do you think about the correlations between all the variables? Which variable should be the most important for prediction of 'Chance of Admit'?

In [6]:
import pandas as pd
admin_df2 = pd.read_csv( 'Admission_Predict.csv' )

In [98]:
admin_df2.columns

Index(['Serial No.', 'GRE Score', 'TOEFL Score', 'University Rating', 'SOP',
       'LOR ', 'CGPA', 'Research', 'Chance of Admit '],
      dtype='object')

In [99]:
admin_df = pd.DataFrame( data = admin_df[ [ 'Serial No.', 'GRE Score', 'TOEFL Score', 'University Rating', 'SOP', 'LOR ', 'CGPA',
                                'Research'] ] )

Pearson Correlation coefficient: 

r = sum( x - m_x )( y - m_y ) / sqrt( sum( x - m_x )^2 sum( y - m_y )^2  )

In [100]:
admin_df2.head( )

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65

In [101]:
admin_corr = pd.DataFrame( columns = admin_df2.columns, index = admin_df2.columns )

for x in range( admin_df2.shape[ 1 ] ):
    
    col_x = admin_df2.columns[ x ]
    
    m_x = np.mean( admin_df2[ '%s' % col_x ] )
    
    for y in range( admin_df2.shape[ 1 ] ):
        
        # Sums
        x_diff, x_diff_sq, y_diff, y_diff_sq = 0, 0, 0, 0
        num_prod = 0
        
        col_y = admin_df2.columns[ y ]
    
        m_y = np.mean( admin_df2[ '%s' % col_y ] )
        
        for row in range( admin_df2.shape[ 0 ] ):
        
            x_0 = admin_df2[ '%s' % col_x ][ row ]
            
            y_0 = admin_df2[ '%s' % col_y ][ row ]
            
            x_diff += x_0 - m_x
            x_diff_sq += ( x_0 - m_x ) ** 2
            
            y_diff += y_0 - m_y
            y_diff_sq += ( y_0 - m_y ) ** 2
            
            num_prod += ( x_0 - m_x ) * ( y_0 - m_y )
            
        PearsonCoeff = num_prod / np.sqrt( x_diff_sq * y_diff_sq  )
        
        admin_corr.loc[ [ '%s' % col_y ], [ '%s' % col_x ] ] = PearsonCoeff

In [104]:
admin_corr

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
Serial No.,1,-0.0975258,-0.147932,-0.169948,-0.166932,-0.0882214,-0.0456084,-0.0631375,0.0423359
GRE Score,-0.0975258,1,0.835977,0.668976,0.612831,0.557555,0.83306,0.580391,0.80261
TOEFL Score,-0.147932,0.835977,1,0.69559,0.657981,0.567721,0.828417,0.489858,0.791594
University Rating,-0.169948,0.668976,0.69559,1,0.734523,0.660123,0.746479,0.447783,0.71125
SOP,-0.166932,0.612831,0.657981,0.734523,1,0.729593,0.718144,0.444029,0.675732
LOR,-0.0882214,0.557555,0.567721,0.660123,0.729593,1,0.670211,0.396859,0.669889
CGPA,-0.0456084,0.83306,0.828417,0.746479,0.718144,0.670211,1,0.521654,0.873289
Research,-0.0631375,0.580391,0.489858,0.447783,0.444029,0.396859,0.521654,1,0.553202
Chance of Admit,0.0423359,0.80261,0.791594,0.71125,0.675732,0.669889,0.873289,0.553202,1

In [105]:
admin_df2.corr( )

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
Serial No.,1.000000,-0.097526,-0.147932,-0.169948,-0.166932,-0.088221,-0.045608,-0.063138,0.042336
GRE Score,-0.097526,1.000000,0.835977,0.668976,0.612831,0.557555,0.833060,0.580391,0.802610
TOEFL Score,-0.147932,0.835977,1.000000,0.695590,0.657981,0.567721,0.828417,0.489858,0.791594
University Rating,-0.169948,0.668976,0.695590,1.000000,0.734523,0.660123,0.746479,0.447783,0.711250
SOP,-0.166932,0.612831,0.657981,0.734523,1.000000,0.729593,0.718144,0.444029,0.675732
LOR,-0.088221,0.557555,0.567721,0.660123,0.729593,1.000000,0.670211,0.396859,0.669889
CGPA,-0.045608,0.833060,0.828417,0.746479,0.718144,0.670211,1.000000,0.521654,0.873289
Research,-0.063138,0.580391,0.489858,0.447783,0.444029,0.396859,0.521654,1.000000,0.553202
Chance of Admit,0.042336,0.802610,0.791594,0.711250,0.675732,0.669889,0.873289,0.553202,1.000000

- Since it seems like 'Serial No.' is just an increasing integer based on the row/record/student number, it's a meaningless vlaue and we shouldn't include it in any of our analysis.

- The diagonal should be 1's because it is comparing a feature to itself

- looking at the last column, the highest value shows the strongest relation to the target. The highest value here is ~0.87 which is the 'CGPA' feature.

# 4. [20 pts] 
Classification of mushrooms, edible or poisonous. Download the assignment01_mushroom_dataset.csv dataset file from the module content. Load the data set in your model development framework, examine the features to see they are all nominal features. The first column is the class which represents the mushroom is poisonous or not. Apply necessary pre-processing such as nominal to numerical conversions. Make sure sanity check the pipeline and perhaps run your favorite baseline classifier first.


Report the performance of your classifier.

In [7]:
shroom_df = pd.read_csv( 'assignment01_mushroom_dataset.csv' )

In [110]:
shroom_df.shape

(8124, 23)

In [113]:
shroom_df.dtypes

class                       object
cap-shape                   object
cap-surface                 object
cap-color                   object
bruises                     object
odor                        object
gill-attachment             object
gill-spacing                object
gill-size                   object
gill-color                  object
stalk-shape                 object
stalk-root                  object
stalk-surface-above-ring    object
stalk-surface-below-ring    object
stalk-color-above-ring      object
stalk-color-below-ring      object
veil-type                   object
veil-color                  object
ring-number                 object
ring-type                   object
spore-print-color           object
population                  object
habitat                     object
dtype: object

In [115]:
shroom_df.head( )

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
1,e,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
4,e,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g

In [8]:
shroom_df.corr( )

Empty DataFrame
Columns: []
Index: []

In [9]:
display( shroom_df[ 'cap-shape' ].value_counts( ) )

x    3656
f    3152
k     828
b     452
s      32
c       4
Name: cap-shape, dtype: int64

In [10]:
for col in shroom_df.columns:
    if shroom_df[col].dtype == object:
        print (col, shroom_df[col].unique())

class ['p' 'e']
cap-shape ['x' 'b' 's' 'f' 'k' 'c']
cap-surface ['s' 'y' 'f' 'g']
cap-color ['n' 'y' 'w' 'g' 'e' 'p' 'b' 'u' 'c' 'r']
bruises ['t' 'f']
odor ['p' 'a' 'l' 'n' 'f' 'c' 'y' 's' 'm']
gill-attachment ['f' 'a']
gill-spacing ['c' 'w']
gill-size ['n' 'b']
gill-color ['k' 'n' 'g' 'p' 'w' 'h' 'u' 'e' 'b' 'r' 'y' 'o']
stalk-shape ['e' 't']
stalk-root ['e' 'c' 'b' 'r' '?']
stalk-surface-above-ring ['s' 'f' 'k' 'y']
stalk-surface-below-ring ['s' 'f' 'y' 'k']
stalk-color-above-ring ['w' 'g' 'p' 'n' 'b' 'e' 'o' 'c' 'y']
stalk-color-below-ring ['w' 'p' 'g' 'b' 'n' 'e' 'y' 'o' 'c']
veil-type ['p']
veil-color ['w' 'n' 'o' 'y']
ring-number ['o' 't' 'n']
ring-type ['p' 'e' 'l' 'f' 'n']
spore-print-color ['k' 'n' 'u' 'h' 'w' 'r' 'o' 'y' 'b']
population ['s' 'n' 'a' 'v' 'y' 'c']
habitat     ['u' 'g' 'm' 'd' 'p' 'w' 'l']

In [11]:
display( shroom_df[ 'stalk-root' ].value_counts( ) )

b    3776
?    2480
e    1120
c     556
r     192
Name: stalk-root, dtype: int64

In [12]:
shroom_df[ 'stalk-root'] = shroom_df['stalk-root'].replace( { '?'  : 'u' } )

In [13]:
def encode_onehot(_df, f):
    _df2 = pd.get_dummies(_df[f], prefix='', prefix_sep='').max(level=0, axis=1).add_prefix(f+' - ')
    df3 = pd.concat([_df, _df2], axis=1)
    df3 = df3.drop([f], axis=1)
    return df3

In [14]:
shroom_df2 = encode_onehot( shroom_df, 'cap-shape' )

In [16]:
for i in range( 2, len( shroom_df.columns ) ):
    shroom_df2 = encode_onehot( shroom_df2, shroom_df.columns[ i ] )

In [26]:
shroom_df2.corr( )

,cap-shape - b,cap-shape - c,cap-shape - f,cap-shape - k,cap-shape - s,cap-shape - x,cap-surface - f,cap-surface - g,cap-surface - s,cap-surface - y,...,population - s,population - v,population - y,habitat - d,habitat - g,habitat - l,habitat - m,habitat - p,habitat - u,habitat - w
cap-shape - b,1.000000,-0.005387,-0.193260,-0.081769,-0.015264,-0.219564,-0.091638,0.018820,0.117712,-0.027947,...,0.158702,-0.168381,-0.120154,-0.182037,0.149151,0.010113,0.374316,-0.095178,-0.052871,-0.037764
cap-shape - c,-0.005387,1.000000,-0.017672,-0.007477,-0.001396,-0.020077,-0.014032,0.249631,-0.015038,0.015893,...,-0.009456,-0.022075,-0.011469,-0.017653,-0.013306,0.065707,-0.004286,-0.008985,-0.004835,-0.003453
cap-shape - f,-0.193260,-0.017672,1.000000,-0.268226,-0.050070,-0.720235,0.064801,-0.006285,-0.093397,0.029076,...,-0.075804,0.034625,0.111346,0.074986,-0.017982,-0.052326,-0.129312,0.021891,0.030636,-0.017450
cap-shape - k,-0.081769,-0.007477,-0.268226,1.000000,-0.021185,-0.304733,-0.158942,0.010863,0.137988,0.015261,...,-0.089360,0.172707,-0.170081,-0.089230,-0.113404,0.235108,-0.065047,0.090538,-0.073380,0.119003
cap-shape - s,-0.015264,-0.001396,-0.050070,-0.021185,1.000000,-0.056884,0.099464,-0.001396,-0.042607,-0.051272,...,-0.026791,0.000341,0.044603,-0.050018,-0.037702,-0.021242,-0.012142,-0.025458,0.288697,-0.009784
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
habitat - l,0.010113,0.065707,-0.052326,0.235108,-0.021242,-0.096639,-0.191987,0.065707,0.190799,-0.006819,...,-0.143906,0.248675,-0.174539,-0.268668,-0.202512,1.000000,-0.065222,-0.136749,-0.073577,-0.052553
habitat - m,0.374316,-0.004286,-0.129312,-0.065047,-0.012142,-0.004529,-0.122077,-0.004286,0.077081,0.039697,...,0.152473,-0.144434,-0.099772,-0.153579,-0.115762,-0.065222,1.000000,-0.078170,-0.042059,-0.030041
habitat - p,-0.095178,-0.008985,0.021891,0.090538,-0.025458,-0.029042,-0.086727,-0.008985,-0.039574,0.117915,...,-0.125366,0.169228,0.040714,-0.322005,-0.242715,-0.136749,-0.078170,1.000000,-0.088184,-0.062986
habitat - u,-0.052871,-0.004835,0.030636,-0.073380,0.288697,0.002845,-0.011913,-0.004835,0.117548,-0.100248,...,0.130450,0.001180,-0.042888,-0.173254,-0.130592,-0.073577,-0.042059,-0.088184,1.000000,-0.033889
habitat - w,-0.037764,-0.003453,-0.017450,0.119003,-0.009784,-0.036493,-0.098365,-0.003453,0.062109,0.031986,...,-0.066282,-0.154742,-0.080392,-0.123748,-0.093276,-0.052553,-0.030041,-0.062986,-0.033889,1.000000

In [27]:
display( shroom_df[ 'class' ].value_counts( ) )

e    4208
p    3916
Name: class, dtype: int64

In [28]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold, StratifiedKFold, train_test_split

In [29]:
def rf_train_test(_X_tr, _X_ts, _y_tr, _y_ts):
    # Create a new random forest classifier, with working 4 parallel cores
    rf = RandomForestClassifier(n_estimators=200, max_depth=5, random_state=None, n_jobs=4)
    # Train on training data
    model = rf.fit(_X_tr, _y_tr)
    # Test on training data
    y_pred = rf.predict(_X_ts)
    # Return accuracy
    return accuracy_score(_y_ts, y_pred)

In [30]:
X = shroom_df2.loc[:, shroom_df2.columns != 'class'].values
y = shroom_df2.loc[:, shroom_df2.columns == 'class'].values.ravel()

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=None)
rf_train_test(X_train, X_test, y_train, y_test)

0.9956923076923077

In [33]:
for i in range(10):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=None)
    print(rf_train_test(X_train, X_test, y_train, y_test))

0.992
0.9938461538461538
0.9870769230769231
0.9926153846153846
0.9907692307692307
0.992
0.9895384615384616
0.9907692307692307
0.9883076923076923
0.9895384615384616

In [34]:
accuracies = []
for i in range(100):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=None)
    accuracies += [rf_train_test(X_train, X_test, y_train, y_test)]

print(f'80% train-test split accuracy is {np.mean(accuracies):.3f} {chr(177)}{np.std(accuracies):.4f}')

80% train-test split accuracy is 0.990 ±0.0025

In [35]:
accuracies = []
kf = KFold(n_splits=10,shuffle=False,random_state=None)
for train_index, test_index in kf.split(X, y):
    acc = rf_train_test(X[train_index], X[test_index], y[train_index], y[test_index])
    accuracies += [acc]

print(f'10-fold cross validation accuracy is {np.mean(accuracies):.3f} {chr(177)}{np.std(accuracies):.4f}')

10-fold cross validation accuracy is 0.990 ±0.0184